apiVersion: v1
kind: Service
metadata:
  name: external-db-service
  namespace: application-ns
spec:
  type: ExternalName
  externalName: my-database-service.database-ns.svc.cluster.local
  ports:
  - port: 5432
